import type { Dictionary } from './en';

const bs: Dictionary = {
  'app.name': 'Islam Quest',

  'common.continue': 'Nastavi',
  'common.back': 'Nazad',
  'common.close': 'Zatvori',
  'common.cancel': 'Odustani',
  'common.start': 'Počni',
  'common.next': 'Dalje',
  'common.done': 'Gotovo',
  'common.check': 'Provjeri',
  'common.retry': 'Pokušaj ponovo',
  'common.loading': 'Učitavanje…',
  'common.locked': 'Zaključano',
  'common.xp': '{xp} XP',
  'common.level': 'Nivo {level}',
  'common.sources': 'Izvori',
  'common.scholarsDiffer': 'Učenjaci se razilaze',
  'common.save': 'Sačuvaj',
  'common.on': 'Uključeno',
  'common.off': 'Isključeno',

  'tabs.home': 'Početna',
  'tabs.quest': 'Avantura',
  'tabs.learn': 'Učenje',
  'tabs.profile': 'Profil',

  'onboarding.step': 'Korak {current} od {total}',
  'onboarding.welcome.title': 'Islam Quest',
  'onboarding.welcome.subtitle': 'Avantura kroz svjetove islamskog znanja. Uči, igraj se, zapamti – i rasti.',
  'onboarding.welcome.cta': 'Započni avanturu',
  'onboarding.language.title': 'Izaberi jezik',
  'onboarding.language.subtitle': 'Možeš ga kasnije promijeniti u postavkama.',
  'onboarding.character.title': 'Napravi svoj lik',
  'onboarding.character.subtitle': 'Ovo si ti na svom putovanju.',
  'onboarding.name.title': 'Kako da te zovemo?',
  'onboarding.name.subtitle': 'Tvoje ime ostaje samo na ovom uređaju.',
  'onboarding.name.placeholder': 'Tvoje ime',
  'onboarding.name.error': 'Unesi ime (1–20 znakova).',
  'onboarding.explain.title': 'Kako avantura funkcioniše',
  'onboarding.explain.learn.title': 'Uči',
  'onboarding.explain.learn.body': 'Kratke lekcije i kazivanja iz pouzdanih izvora.',
  'onboarding.explain.play.title': 'Igraj se',
  'onboarding.explain.play.body': 'Kvizovi, spajanje, redanje, memorija i odluke.',
  'onboarding.explain.remember.title': 'Zapamti',
  'onboarding.explain.remember.body': 'Teža pitanja se kasnije vraćaju da ih zaista zapamtiš.',
  'onboarding.explain.reward.title': 'Rasti',
  'onboarding.explain.reward.body': 'Skupljaj XP, napreduj, osvajaj značke i otključavaj nove svjetove.',
  'onboarding.start.title': 'Tvoja prva avantura te čeka',
  'onboarding.start.body': 'Svijet namaza je otvoren. Otkrij šta je namaz i zašto muslimani klanjaju.',
  'onboarding.start.cta': 'Započni prvu avanturu',
  'onboarding.start.later': 'Prvo razgledaj',

  'character.title': 'Tvoj lik',
  'character.skin': 'Boja kože',
  'character.hair': 'Kosa',
  'character.hairColor': 'Boja kose',
  'character.headwear': 'Pokrivalo za glavu',
  'character.outfit': 'Odjeća',
  'character.outfitColor': 'Boja odjeće',
  'character.accessory': 'Dodatak',
  'character.saved': 'Lik sačuvan',
  'character.hair.short': 'Kratka',
  'character.hair.curly': 'Kovrdžava',
  'character.hair.long': 'Duga',
  'character.hair.buzz': 'Jako kratka',
  'character.hair.bun': 'Punđa',
  'character.headwear.none': 'Bez',
  'character.headwear.kufi': 'Kapica',
  'character.headwear.hijab': 'Hidžab',
  'character.headwear.cap': 'Kačket',
  'character.outfit.thobe': 'Dželabija',
  'character.outfit.hoodie': 'Duks',
  'character.outfit.jacket': 'Jakna',
  'character.outfit.abaya': 'Abaja',
  'character.accessory.none': 'Bez',
  'character.accessory.glasses': 'Naočale',
  'character.accessory.backpack': 'Ranac',
  'character.accessory.scarf': 'Šal',
  'character.accessory.lantern': 'Fenjer',
  'character.option': '{group}: {value}',

  'home.greeting': 'Es-selamu alejkum, {name}!',
  'home.subtitle': 'Šta ćeš danas otkriti?',
  'home.daily.title': 'Dnevni izazov',
  'home.daily.body': 'Svaki dan jedan kratki izazov.',
  'home.daily.done': 'Završeno za danas – vidimo se sutra!',
  'home.continue.title': 'Nastavi svoju avanturu',
  'home.continue.allDone': 'Završio si sve avanture. Svaka čast!',
  'home.worlds': 'Tvoji svjetovi',
  'home.review.title': 'Ponovimo',
  'home.review.count': 'Pitanja na čekanju: {count}',
  'home.review.empty': 'Trenutno nema ništa za ponavljanje',
  'home.ramadan': 'Ramazansko putovanje',
  'home.ramadan.body': 'Kalendar i praćenje dobrih djela',

  'streak.label': 'Niz',
  'streak.days': '{count} dana',
  'streak.day': '{count} dan',
  'streak.today': 'Danas si učio',
  'streak.notToday': 'Nauči nešto danas da zadržiš niz',
  'streak.note': 'Tvoj niz raste kada završiš lekciju, avanturu, ponavljanje ili dnevni izazov.',

  'map.title': 'Mapa svjetova',
  'map.subtitle': 'Završi avanture da otvoriš nove svjetove.',
  'map.progress': '{done}/{total} avantura',
  'map.lockedRequirement': 'Završi {count} avanture u „{world}“ da otključaš',
  'map.complete': 'Svijet završen',

  'world.quests': 'Avanture',
  'world.lessons': 'Lekcije u ovom svijetu',
  'world.locked': 'Ovaj svijet je još zaključan.',
  'world.play': 'Igraj',
  'world.replay': 'Igraj ponovo',
  'world.lockedQuest': 'Prvo završi prethodnu avanturu',
  'world.current': 'Sljedeće',
  'quest.kind.lesson': 'Lekcija',
  'quest.kind.story': 'Kazivanje',
  'quest.kind.game': 'Mini igre',
  'quest.kind.memorization': 'Učenje napamet',
  'quest.status.completed': 'Završeno',
  'quest.status.available': 'Dostupno',
  'quest.status.locked': 'Zaključano',
  'quest.steps': '{count} koraka',

  'player.exitTitle': 'Napustiti avanturu?',
  'player.exitBody': 'Dosadašnji odgovori se neće računati kao završena avantura.',
  'player.exit': 'Napusti',
  'player.stay': 'Ostani',
  'player.label.interactive': 'Šta ti misliš?',
  'player.label.challenge': 'Mini izazov',
  'player.label.quiz': 'Kviz',
  'player.correct': 'Tačno!',
  'player.notQuite': 'Ne baš',
  'player.correctAnswer': 'Tačan odgovor: {answer}',
  'player.learnedTitle': 'Šta smo naučili?',
  'player.story': 'Kazivanje',
  'player.addedToReview': 'Dodano na tvoju listu za ponavljanje',
  'player.notFound': 'Ova avantura nije pronađena.',
  'player.locked': 'Ova avantura je još zaključana.',

  'q.true': 'Tačno',
  'q.false': 'Netačno',
  'q.ordering.hint': 'Dodirni stavke pravilnim redom.',
  'q.ordering.reset': 'Počni ispočetka',
  'q.matching.hint': 'Dodirni stavku lijevo, pa njen par desno.',
  'q.matching.mistakes': 'Greške: {count}',
  'q.memory.hint': 'Okreni dvije karte da pronađeš par.',
  'q.memory.moves': 'Potezi: {count}',
  'q.missingWord.hint': 'Izaberi riječ koja nedostaje.',
  'q.ayahOrder.hint': 'Dodirni ajete pravilnim redom.',
  'q.scenario.title': 'Šta bi ti uradio?',

  'recite.title': 'Nauči napamet: {surah}',
  'recite.hint': 'Pročitaj svaki ajet polahko i ponovi ga tri puta. Nakon svakog ponavljanja dodirni ajet.',
  'recite.repeat': '{count}/3',
  'recite.hideText': 'Provjeri se',
  'recite.showText': 'Prikaži tekst',
  'recite.play': 'Slušaj',
  'recite.stop': 'Stop',
  'recite.audioUnavailable': 'Za slušanje učenja potrebna je internet veza.',
  'recite.done': 'Vježbao sam ovu suru',
  'recite.makki': 'Mekanska',
  'recite.madani': 'Medinska',
  'recite.ayahs': '{count} ajeta',
  'recite.source': 'Arapski tekst: Tanzil (Uthmani). Prijevod: {translation}.',
  'recite.basmalaNote': 'Počinjemo s Bismillom.',
  'recite.remaining': 'Ponovi svaki ajet 3 puta da nastaviš.',

  'tracing.title': 'Obrubi harf',
  'tracing.hint': 'Prstom prati oblik harfa.',
  'tracing.clear': 'Obriši',
  'tracing.next': 'Sljedeći harf',
  'tracing.listen': 'Slušaj',
  'tracing.keepGoing': 'Nastavi pratiti…',
  'tracing.great': 'Odlično!',
  'tracing.progress': 'Harf {current} od {total}',

  'lesson.listen': 'Slušaj',
  'lesson.done': 'Pročitao sam',
  'lesson.locked': 'Otključaj ovu lekciju u avanturi „{quest}“.',
  'lesson.notFound': 'Ova lekcija nije pronađena.',
  'lesson.completed': 'Lekcija završena',

  'reward.title': 'Avantura završena!',
  'reward.score': '{correct} od {total} tačno',
  'reward.lines.questComplete': 'Avantura završena',
  'reward.lines.perfectBonus': 'Bonus za bez greške',
  'reward.lines.worldComplete': 'Svijet završen',
  'reward.lines.answers': 'Tačni odgovori i lekcije',
  'reward.noXp': 'XP si ovdje već osvojio – ponovno vježbanje ti ipak pomaže da zapamtiš!',
  'reward.levelUp': 'Novi nivo! Sada si na nivou {level}.',
  'reward.newBadge': 'Nova značka otključana!',
  'reward.worldUnlocked': 'Novi svijet otključan: {world}',
  'reward.backToMap': 'Nazad na mapu',
  'reward.reviewMistakes': 'Ponovi greške',
  'reward.xpTotal': '+{xp} XP',
  'reward.nextQuest': 'Sljedeća avantura',
  'celebrate.levelTitle': 'Novi nivo!',
  'celebrate.levelBody': 'Dostigao si nivo {level}. Nastavi učiti – svaka lekcija te čini jačim!',

  'learn.title': 'Učenje',
  'learn.subtitle': 'Ponovo pročitaj lekcije i vježbaj ono što ti je bilo teško.',
  'learn.review.title': 'Ponovimo',
  'learn.review.body': 'Promašena pitanja se vraćaju u pravo vrijeme da ih zaista zapamtiš.',
  'learn.review.cta': 'Započni ponavljanje',
  'learn.review.due': '{count} sada na redu',
  'learn.review.none': 'Nema pitanja na redu',
  'learn.topics': 'Teme',
  'learn.lessonsCount': '{done}/{total} lekcija',
  'learn.weakTopics': 'Teme za vježbu',
  'learn.quran': 'Učenje Kur\'ana napamet',
  'learn.practised': 'Vježbano {count}×',
  'learn.notPractised': 'Još nije vježbano',
  'learn.worldLocked': 'Otključaj ovaj svijet na mapi',

  'review.title': 'Ponovimo',
  'review.intro': 'Ova pitanja su ti bila teška. Pokušajmo ponovo!',
  'review.empty.title': 'Sve je ponovljeno!',
  'review.empty.body': 'Trenutno nema ništa za ponavljanje.',
  'review.empty.next': 'Sljedeće ponavljanje: {date}',
  'review.empty.noItems': 'Kada promašiš pitanje, kasnije će se pojaviti ovdje.',
  'review.start': 'Počni ({count})',
  'review.doneTitle': 'Ponavljanje završeno',
  'review.doneBody': 'Zapamtio si {correct} od {total}. Iz grešaka učimo!',
  'review.mastered': 'Savladano',
  'review.box': 'Nivo {box}',

  'daily.title': 'Dnevni izazov',
  'daily.kind.question': 'Pitanje dana',
  'daily.kind.miniQuiz': 'Mini kviz',
  'daily.kind.memory': 'Igra memorije',
  'daily.kind.fact': 'Da li si znao?',
  'daily.kind.scenario': 'Šta bi ti uradio?',
  'daily.doneTitle': 'Dnevni izazov završen!',
  'daily.alreadyDone': 'Današnji izazov si već završio. Sutra te čeka novi!',
  'daily.factThenQuestion': 'Pročitaj zanimljivost, pa odgovori na pitanje.',

  'profile.title': 'Profil',
  'profile.edit': 'Uredi lik',
  'profile.xpToNext': 'Još {xp} XP do nivoa {level}',
  'profile.badges': 'Značke',
  'profile.badgesCount': '{earned}/{total}',
  'profile.seeAll': 'Prikaži sve',
  'profile.stats': 'Statistika',
  'profile.settings': 'Postavke',
  'stats.quests': 'Završene avanture',
  'stats.lessons': 'Pročitane lekcije',
  'stats.answers': 'Tačni odgovori',
  'stats.accuracy': 'Tačnost',
  'stats.longestStreak': 'Najduži niz',
  'stats.reviews': 'Zapamćena ponavljanja',
  'stats.daily': 'Dnevni izazovi',

  'badges.title': 'Značke',
  'badges.locked': 'Još nije osvojena',
  'badges.earnedOn': 'Osvojena {date}',
  'badge.first_lesson.name': 'Prva lekcija',
  'badge.first_lesson.desc': 'Pročitaj svoju prvu lekciju.',
  'badge.first_quest.name': 'Prva avantura',
  'badge.first_quest.desc': 'Završi svoju prvu avanturu.',
  'badge.prayer_explorer.name': 'Istraživač namaza',
  'badge.prayer_explorer.desc': 'Završi Svijet namaza.',
  'badge.story_seeker.name': 'Tragač za kazivanjima',
  'badge.story_seeker.desc': 'Završi Svijet poslanika.',
  'badge.quran_explorer.name': 'Istraživač Kur\'ana',
  'badge.quran_explorer.desc': 'Završi Svijet Kur\'ana.',
  'badge.akhlaq_hero.name': 'Heroj ahlaka',
  'badge.akhlaq_hero.desc': 'Završi Svijet ahlaka.',
  'badge.ramadan_learner.name': 'Ramazanski učenik',
  'badge.ramadan_learner.desc': 'Završi Svijet ramazana.',
  'badge.arabic_beginner.name': 'Početnik arapskog',
  'badge.arabic_beginner.desc': 'Završi Svijet arapskog.',
  'badge.streak_7.name': 'Niz od 7 dana',
  'badge.streak_7.desc': 'Uči 7 dana zaredom.',
  'badge.streak_30.name': 'Niz od 30 dana',
  'badge.streak_30.desc': 'Uči 30 dana zaredom.',
  'badge.daily_learner.name': 'Svakodnevni učenik',
  'badge.daily_learner.desc': 'Završi 7 dnevnih izazova.',
  'badge.review_champion.name': 'Šampion ponavljanja',
  'badge.review_champion.desc': 'Zapamti 10 pitanja u ponavljanju.',
  'badge.perfect_score.name': 'Bez greške',
  'badge.perfect_score.desc': 'Završi avanturu bez ijedne greške.',
  'badge.world_explorer.name': 'Istraživač svjetova',
  'badge.world_explorer.desc': 'Otključaj svih šest svjetova.',
  'badge.knowledge_master.name': 'Majstor znanja',
  'badge.knowledge_master.desc': 'Završi sve avanture.',

  'settings.title': 'Postavke',
  'settings.section.general': 'Općenito',
  'settings.section.sound': 'Zvuk',
  'settings.section.accessibility': 'Pristupačnost',
  'settings.section.notifications': 'Podsjetnici',
  'settings.section.info': 'Informacije',
  'settings.section.data': 'Podaci',
  'settings.language': 'Jezik',
  'settings.sound': 'Zvučni efekti',
  'settings.soundDesc': 'Blagi zvukovi za dodire, odgovore i nagrade.',
  'settings.ambient': 'Zvuk okruženja',
  'settings.ambientDesc': 'Miran zvuk vjetra u pozadini. Bez muzike.',
  'settings.haptics': 'Vibracija',
  'settings.reducedMotion': 'Smanji animacije',
  'settings.reducedMotionDesc': 'Manje pokreta na ekranu.',
  'settings.largeText': 'Veći tekst',
  'settings.notif.dailyQuest': 'Podsjetnik za dnevnu avanturu',
  'settings.notif.dailyReview': 'Podsjetnik za ponavljanje',
  'settings.notif.dailyChallenge': 'Podsjetnik za dnevni izazov',
  'settings.notif.desc': 'Jedan blagi podsjetnik dnevno. Svi podsjetnici su neobavezni.',
  'settings.notif.denied': 'Podsjetnici su blokirani. Obavještenja možeš dozvoliti u postavkama telefona.',
  'settings.notif.unavailable': 'Podsjetnici nisu dostupni na ovom uređaju.',
  'settings.about': 'O aplikaciji Islam Quest',
  'settings.privacy': 'Privatnost',
  'settings.sources': 'Izvori',
  'settings.reset': 'Poništi napredak',
  'settings.resetDesc': 'Briše lik, XP, značke i napredak na ovom uređaju.',
  'settings.resetConfirmTitle': 'Poništiti sav napredak?',
  'settings.resetConfirmBody': 'Ovo briše sve na ovom uređaju i ne može se vratiti.',
  'settings.resetConfirm': 'Da, poništi',
  'settings.version': 'Verzija {version}',

  'about.title': 'O aplikaciji Islam Quest',
  'about.p1': 'Islam Quest je besplatna obrazovna avantura za djecu i mlade. Kroz kratke lekcije i igre uči osnove namaza, kazivanja o poslanicima, Kur\'an, lijep ahlak, ramazan i arapski jezik.',
  'about.p2': 'Nema reklama, nema kupovina i nema korisničkih računa. Sav sadržaj radi bez interneta.',
  'about.p3': 'Islam Quest je pomoćnik u učenju. Ne daje fetve i ne zamjenjuje roditelje, učitelje, imame niti pravu nastavu Kur\'ana i arapskog. Gdje učenjaci imaju različita mišljenja, aplikacija to i kaže.',
  'privacy.title': 'Privatnost',
  'privacy.p1': 'Islam Quest ne prikuplja, ne šalje i ne prodaje lične podatke. Nema reklama, analitike niti praćenja.',
  'privacy.p2': 'Tvoje ime, lik i napredak čuvaju se samo na ovom uređaju. Poništavanje napretka ili deinstalacija ih briše.',
  'privacy.p3': 'Aplikacija koristi internet samo ako dodirneš „Slušaj“ kod učenja Kur\'ana; zvuk se tada učitava s Islamic Network CDN-a. Sve ostalo radi bez interneta.',
  'privacy.p4': 'Podsjetnici su lokalna obavještenja na tvom uređaju. Možeš ih isključiti u svakom trenutku.',
  'sources.title': 'Izvori',
  'sources.intro': 'Vjerski sadržaj u ovoj aplikaciji zasnovan je na Kur\'anu i poznatim zbirkama hadisa. Svaka lekcija navodi svoje izvore.',
  'sources.quran': 'Tekst Kur\'ana: projekat Tanzil (tanzil.net), osmansko pismo, korišten bez izmjena.',
  'sources.translations': 'Prijevodi Kur\'ana: Saheeh International (engleski), Bubenheim i Elyas (njemački), Besim Korkut (bosanski).',
  'sources.hadith': 'Hadiski izvori: Sahih el-Buhari, Sahih Muslim, Sunen Ebu Davud, Džami’ et-Tirmizi (standardno numerisanje).',
  'sources.seerah': 'Sira: Ibn Hišam, Es-Sire en-Nebevijje.',
  'sources.recitation': 'Neobavezno učenje: Mishary Rashid Alafasy putem cdn.islamic.network.',
  'sources.disclaimer': 'Kazivanja su prepričana jednostavnim riječima, bez dodavanja događaja ili dijaloga. Poslanici se nikada ne prikazuju na slikama.',

  'notif.dailyQuest.title': 'Tvoja avantura čeka',
  'notif.dailyQuest.body': 'Kratka lekcija danas održava tvoju avanturu.',
  'notif.dailyReview.title': 'Vrijeme za ponavljanje',
  'notif.dailyReview.body': 'Nekoliko težih pitanja te čeka.',
  'notif.dailyChallenge.title': 'Dnevni izazov',
  'notif.dailyChallenge.body': 'Današnji izazov je spreman. Možeš li ga riješiti?',
  'notif.channel': 'Podsjetnici za učenje',

  'ramadan.title': 'Ramazansko putovanje',
  'ramadan.intro': 'Bilježi svoja dobra djela za svaki dan ramazana. Svako malo djelo se računa!',
  'ramadan.safety': 'O vježbanju posta uvijek odlučuješ zajedno s roditeljima. Tvoje zdravlje je na prvom mjestu.',
  'ramadan.day': 'Dan {day}',
  'ramadan.deedsFor': 'Dobra djela {day}. dana',
  'ramadan.total': 'Do sada {count} dobrih djela',
  'ramadan.tip': 'Savjet dana',
  'ramadan.learnMore': 'Saznaj više o ramazanu',
  'ramadan.locked': 'Otključaj Svijet ramazana da saznaš više o ovom mjesecu.',

  'error.title': 'Nešto nije u redu',
  'error.body': 'Ne brini – tvoj napredak je siguran. Pokušaj ponovo.',
  'notFound.title': 'Stranica nije pronađena',
  'notFound.body': 'Ovo mjesto ne postoji na mapi.',
  'notFound.home': 'Na početnu',

  'a11y.xpBar': '{xp} od {total} XP do sljedećeg nivoa',
  'a11y.stars': '{count} od 3 zvjezdice',
  'a11y.speak': 'Pusti izgovor',
  'a11y.closeQuest': 'Zatvori avanturu',
  'a11y.back': 'Nazad',
  'a11y.selected': 'odabrano',
  'a11y.correct': 'tačno',
  'a11y.incorrect': 'netačno',
  'a11y.card': 'Karta {index}',
  'a11y.hiddenCard': 'Skrivena karta {index}',
  'a11y.progress': 'Napredak {percent} posto',
  'a11y.avatar': 'Tvoj lik',
};

export default bs;
