import type { Dictionary } from './en';

const de: Dictionary = {
  'app.name': 'Islam Quest',

  'common.continue': 'Weiter',
  'common.back': 'Zurück',
  'common.close': 'Schließen',
  'common.cancel': 'Abbrechen',
  'common.start': 'Starten',
  'common.next': 'Weiter',
  'common.done': 'Fertig',
  'common.check': 'Prüfen',
  'common.retry': 'Nochmal versuchen',
  'common.loading': 'Lädt…',
  'common.locked': 'Gesperrt',
  'common.xp': '{xp} XP',
  'common.level': 'Stufe {level}',
  'common.sources': 'Quellen',
  'common.scholarsDiffer': 'Gelehrte sind sich uneinig',
  'common.save': 'Speichern',
  'common.on': 'An',
  'common.off': 'Aus',

  'tabs.home': 'Start',
  'tabs.quest': 'Abenteuer',
  'tabs.learn': 'Lernen',
  'tabs.profile': 'Profil',

  'onboarding.step': 'Schritt {current} von {total}',
  'onboarding.welcome.title': 'Islam Quest',
  'onboarding.welcome.subtitle': 'Ein Abenteuer durch die Welten des islamischen Wissens. Lernen, spielen, merken – und wachsen.',
  'onboarding.welcome.cta': 'Abenteuer beginnen',
  'onboarding.language.title': 'Wähle deine Sprache',
  'onboarding.language.subtitle': 'Du kannst sie später in den Einstellungen ändern.',
  'onboarding.character.title': 'Erstelle deine Figur',
  'onboarding.character.subtitle': 'Das bist du auf deiner Reise.',
  'onboarding.name.title': 'Wie sollen wir dich nennen?',
  'onboarding.name.subtitle': 'Dein Name bleibt nur auf diesem Gerät.',
  'onboarding.name.placeholder': 'Dein Name',
  'onboarding.name.error': 'Bitte gib einen Namen ein (1–20 Zeichen).',
  'onboarding.explain.title': 'So funktioniert das Abenteuer',
  'onboarding.explain.learn.title': 'Lernen',
  'onboarding.explain.learn.body': 'Kurze Lektionen und Geschichten aus verlässlichen Quellen.',
  'onboarding.explain.play.title': 'Spielen',
  'onboarding.explain.play.body': 'Quiz, Zuordnen, Sortieren, Memory und Entscheidungen.',
  'onboarding.explain.remember.title': 'Merken',
  'onboarding.explain.remember.body': 'Knifflige Fragen kommen später wieder, damit du sie wirklich behältst.',
  'onboarding.explain.reward.title': 'Wachsen',
  'onboarding.explain.reward.body': 'Sammle XP, steige auf, verdiene Abzeichen und öffne neue Welten.',
  'onboarding.start.title': 'Dein erstes Abenteuer wartet',
  'onboarding.start.body': 'Die Welt des Gebets ist offen. Entdecke, was das Gebet ist und warum Muslime beten.',
  'onboarding.start.cta': 'Erstes Abenteuer starten',
  'onboarding.start.later': 'Erst umschauen',

  'character.title': 'Deine Figur',
  'character.skin': 'Hautton',
  'character.hair': 'Haare',
  'character.hairColor': 'Haarfarbe',
  'character.headwear': 'Kopfbedeckung',
  'character.outfit': 'Kleidung',
  'character.outfitColor': 'Kleidungsfarbe',
  'character.accessory': 'Accessoire',
  'character.saved': 'Figur gespeichert',
  'character.hair.short': 'Kurz',
  'character.hair.curly': 'Lockig',
  'character.hair.long': 'Lang',
  'character.hair.buzz': 'Kurzhaar',
  'character.hair.bun': 'Dutt',
  'character.headwear.none': 'Keine',
  'character.headwear.kufi': 'Kufi',
  'character.headwear.hijab': 'Hidschab',
  'character.headwear.cap': 'Kappe',
  'character.outfit.thobe': 'Thobe',
  'character.outfit.hoodie': 'Kapuzenpulli',
  'character.outfit.jacket': 'Jacke',
  'character.outfit.abaya': 'Abaya',
  'character.accessory.none': 'Keins',
  'character.accessory.glasses': 'Brille',
  'character.accessory.backpack': 'Rucksack',
  'character.accessory.scarf': 'Schal',
  'character.accessory.lantern': 'Laterne',
  'character.option': '{group}: {value}',

  'home.greeting': 'As-salamu alaikum, {name}!',
  'home.subtitle': 'Was entdeckst du heute?',
  'home.daily.title': 'Tägliche Herausforderung',
  'home.daily.body': 'Jeden Tag eine kurze Herausforderung.',
  'home.daily.done': 'Heute geschafft – bis morgen!',
  'home.continue.title': 'Setze dein Abenteuer fort',
  'home.continue.allDone': 'Du hast alle Abenteuer abgeschlossen. Großartig!',
  'home.worlds': 'Deine Welten',
  'home.review.title': 'Wiederholen',
  'home.review.count': '{count} Fragen warten',
  'home.review.empty': 'Gerade gibt es nichts zu wiederholen',
  'home.ramadan': 'Ramadan-Reise',
  'home.ramadan.body': 'Kalender und Gute-Taten-Tracker',

  'streak.label': 'Serie',
  'streak.days': '{count} Tage',
  'streak.day': '{count} Tag',
  'streak.today': 'Du hast heute gelernt',
  'streak.notToday': 'Lerne heute etwas, um deine Serie zu halten',
  'streak.note': 'Deine Serie wächst, wenn du eine Lektion, ein Abenteuer, eine Wiederholung oder die tägliche Herausforderung abschließt.',

  'map.title': 'Weltkarte',
  'map.subtitle': 'Schließe Abenteuer ab, um neue Welten zu öffnen.',
  'map.progress': '{done}/{total} Abenteuer',
  'map.lockedRequirement': 'Schließe {count} Abenteuer in „{world}“ ab, um sie zu öffnen',
  'map.complete': 'Welt abgeschlossen',

  'world.quests': 'Abenteuer',
  'world.lessons': 'Lektionen in dieser Welt',
  'world.locked': 'Diese Welt ist noch gesperrt.',
  'world.play': 'Spielen',
  'world.replay': 'Nochmal spielen',
  'world.lockedQuest': 'Schließe zuerst das vorherige Abenteuer ab',
  'world.current': 'Als Nächstes',
  'quest.kind.lesson': 'Lektion',
  'quest.kind.story': 'Geschichte',
  'quest.kind.game': 'Minispiele',
  'quest.kind.memorization': 'Auswendiglernen',
  'quest.status.completed': 'Abgeschlossen',
  'quest.status.available': 'Verfügbar',
  'quest.status.locked': 'Gesperrt',
  'quest.steps': '{count} Schritte',

  'player.exitTitle': 'Abenteuer verlassen?',
  'player.exitBody': 'Deine bisherigen Antworten zählen nicht als abgeschlossenes Abenteuer.',
  'player.exit': 'Verlassen',
  'player.stay': 'Bleiben',
  'player.label.interactive': 'Was denkst du?',
  'player.label.challenge': 'Mini-Herausforderung',
  'player.label.quiz': 'Quiz',
  'player.correct': 'Richtig!',
  'player.notQuite': 'Nicht ganz',
  'player.correctAnswer': 'Richtige Antwort: {answer}',
  'player.learnedTitle': 'Was haben wir gelernt?',
  'player.story': 'Geschichte',
  'player.addedToReview': 'Zu deiner Wiederholungsliste hinzugefügt',
  'player.notFound': 'Dieses Abenteuer wurde nicht gefunden.',
  'player.locked': 'Dieses Abenteuer ist noch gesperrt.',

  'q.true': 'Richtig',
  'q.false': 'Falsch',
  'q.ordering.hint': 'Tippe die Einträge in der richtigen Reihenfolge an.',
  'q.ordering.reset': 'Neu beginnen',
  'q.matching.hint': 'Tippe links einen Eintrag an, dann seinen Partner rechts.',
  'q.matching.mistakes': 'Fehler: {count}',
  'q.memory.hint': 'Decke zwei Karten auf, um ein Paar zu finden.',
  'q.memory.moves': 'Züge: {count}',
  'q.missingWord.hint': 'Wähle das fehlende Wort.',
  'q.ayahOrder.hint': 'Tippe die Verse in der richtigen Reihenfolge an.',
  'q.scenario.title': 'Was würdest du tun?',

  'recite.title': 'Auswendig lernen: {surah}',
  'recite.hint': 'Lies jeden Vers langsam und wiederhole ihn dreimal. Tippe nach jeder Wiederholung auf den Vers.',
  'recite.repeat': '{count}/3',
  'recite.hideText': 'Mich selbst prüfen',
  'recite.showText': 'Text zeigen',
  'recite.play': 'Anhören',
  'recite.stop': 'Stopp',
  'recite.audioUnavailable': 'Zum Anhören der Rezitation brauchst du eine Internetverbindung.',
  'recite.done': 'Ich habe diese Sure geübt',
  'recite.makki': 'Mekkanisch',
  'recite.madani': 'Medinensisch',
  'recite.ayahs': '{count} Verse',
  'recite.source': 'Arabischer Text: Tanzil (Uthmani). Übersetzung: {translation}.',
  'recite.basmalaNote': 'Wir beginnen mit Bismillah.',
  'recite.remaining': 'Wiederhole jeden Vers 3-mal, um weiterzumachen.',

  'tracing.title': 'Fahre den Buchstaben nach',
  'tracing.hint': 'Folge der Form des Buchstabens mit deinem Finger.',
  'tracing.clear': 'Löschen',
  'tracing.next': 'Nächster Buchstabe',
  'tracing.listen': 'Anhören',
  'tracing.keepGoing': 'Weiter nachfahren…',
  'tracing.great': 'Toll nachgefahren!',
  'tracing.progress': 'Buchstabe {current} von {total}',

  'lesson.listen': 'Anhören',
  'lesson.done': 'Ich habe es gelesen',
  'lesson.locked': 'Schalte diese Lektion im Abenteuer „{quest}“ frei.',
  'lesson.notFound': 'Diese Lektion wurde nicht gefunden.',
  'lesson.completed': 'Lektion abgeschlossen',

  'reward.title': 'Abenteuer geschafft!',
  'reward.score': '{correct} von {total} richtig',
  'reward.lines.questComplete': 'Abenteuer abgeschlossen',
  'reward.lines.perfectBonus': 'Bonus für fehlerfrei',
  'reward.lines.worldComplete': 'Welt abgeschlossen',
  'reward.lines.answers': 'Richtige Antworten & Lektionen',
  'reward.noXp': 'Die XP hast du hier schon verdient – erneutes Üben hilft dir trotzdem beim Merken!',
  'reward.levelUp': 'Aufgestiegen! Du bist jetzt Stufe {level}.',
  'reward.newBadge': 'Neues Abzeichen freigeschaltet!',
  'reward.worldUnlocked': 'Neue Welt geöffnet: {world}',
  'reward.backToMap': 'Zurück zur Karte',
  'reward.reviewMistakes': 'Fehler wiederholen',
  'reward.xpTotal': '+{xp} XP',
  'reward.nextQuest': 'Nächstes Abenteuer',
  'celebrate.levelTitle': 'Aufgestiegen!',
  'celebrate.levelBody': 'Du hast Stufe {level} erreicht. Lerne weiter – jede Lektion macht dich stärker!',

  'learn.title': 'Lernen',
  'learn.subtitle': 'Lies Lektionen erneut und übe, was dir schwerfiel.',
  'learn.review.title': 'Wiederholen',
  'learn.review.body': 'Verpasste Fragen kommen zur richtigen Zeit wieder, damit du sie wirklich behältst.',
  'learn.review.cta': 'Wiederholung starten',
  'learn.review.due': '{count} jetzt fällig',
  'learn.review.none': 'Keine Fragen fällig',
  'learn.topics': 'Themen',
  'learn.lessonsCount': '{done}/{total} Lektionen',
  'learn.weakTopics': 'Themen zum Üben',
  'learn.quran': 'Koran auswendig lernen',
  'learn.practised': '{count}× geübt',
  'learn.notPractised': 'Noch nicht geübt',
  'learn.worldLocked': 'Öffne diese Welt auf der Karte',

  'review.title': 'Wiederholen',
  'review.intro': 'Diese Fragen waren knifflig. Versuchen wir es noch einmal!',
  'review.empty.title': 'Alles erledigt!',
  'review.empty.body': 'Gerade gibt es nichts zu wiederholen.',
  'review.empty.next': 'Nächste Wiederholung: {date}',
  'review.empty.noItems': 'Wenn du eine Frage verpasst, erscheint sie später hier.',
  'review.start': 'Starten ({count})',
  'review.doneTitle': 'Wiederholung geschafft',
  'review.doneBody': 'Du hast dir {correct} von {total} gemerkt. Aus Fehlern lernen wir!',
  'review.mastered': 'Gemeistert',
  'review.box': 'Stufe {box}',

  'daily.title': 'Tägliche Herausforderung',
  'daily.kind.question': 'Frage des Tages',
  'daily.kind.miniQuiz': 'Mini-Quiz',
  'daily.kind.memory': 'Memory-Spiel',
  'daily.kind.fact': 'Wusstest du?',
  'daily.kind.scenario': 'Was würdest du tun?',
  'daily.doneTitle': 'Tägliche Herausforderung geschafft!',
  'daily.alreadyDone': 'Du hast die heutige Herausforderung schon geschafft. Morgen gibt es eine neue!',
  'daily.factThenQuestion': 'Lies die Info und beantworte dann die Frage.',

  'profile.title': 'Profil',
  'profile.edit': 'Figur bearbeiten',
  'profile.xpToNext': 'Noch {xp} XP bis Stufe {level}',
  'profile.badges': 'Abzeichen',
  'profile.badgesCount': '{earned}/{total}',
  'profile.seeAll': 'Alle ansehen',
  'profile.stats': 'Statistik',
  'profile.settings': 'Einstellungen',
  'stats.quests': 'Abenteuer abgeschlossen',
  'stats.lessons': 'Lektionen gelesen',
  'stats.answers': 'Richtige Antworten',
  'stats.accuracy': 'Genauigkeit',
  'stats.longestStreak': 'Längste Serie',
  'stats.reviews': 'Wiederholungen gemerkt',
  'stats.daily': 'Tägliche Herausforderungen',

  'badges.title': 'Abzeichen',
  'badges.locked': 'Noch nicht verdient',
  'badges.earnedOn': 'Verdient am {date}',
  'badge.first_lesson.name': 'Erste Lektion',
  'badge.first_lesson.desc': 'Lies deine erste Lektion.',
  'badge.first_quest.name': 'Erstes Abenteuer',
  'badge.first_quest.desc': 'Schließe dein erstes Abenteuer ab.',
  'badge.prayer_explorer.name': 'Gebets-Entdecker',
  'badge.prayer_explorer.desc': 'Schließe die Welt des Gebets ab.',
  'badge.story_seeker.name': 'Geschichten-Sucher',
  'badge.story_seeker.desc': 'Schließe die Welt der Propheten ab.',
  'badge.quran_explorer.name': 'Koran-Entdecker',
  'badge.quran_explorer.desc': 'Schließe die Welt des Korans ab.',
  'badge.akhlaq_hero.name': 'Charakter-Held',
  'badge.akhlaq_hero.desc': 'Schließe die Welt des Charakters ab.',
  'badge.ramadan_learner.name': 'Ramadan-Lerner',
  'badge.ramadan_learner.desc': 'Schließe die Welt des Ramadan ab.',
  'badge.arabic_beginner.name': 'Arabisch-Anfänger',
  'badge.arabic_beginner.desc': 'Schließe die Welt des Arabischen ab.',
  'badge.streak_7.name': '7-Tage-Serie',
  'badge.streak_7.desc': 'Lerne an 7 Tagen hintereinander.',
  'badge.streak_30.name': '30-Tage-Serie',
  'badge.streak_30.desc': 'Lerne an 30 Tagen hintereinander.',
  'badge.daily_learner.name': 'Täglich dabei',
  'badge.daily_learner.desc': 'Schließe 7 tägliche Herausforderungen ab.',
  'badge.review_champion.name': 'Wiederholungs-Champion',
  'badge.review_champion.desc': 'Merke dir 10 Fragen in der Wiederholung.',
  'badge.perfect_score.name': 'Fehlerfrei',
  'badge.perfect_score.desc': 'Schließe ein Abenteuer ohne Fehler ab.',
  'badge.world_explorer.name': 'Welten-Entdecker',
  'badge.world_explorer.desc': 'Öffne alle sechs Welten.',
  'badge.knowledge_master.name': 'Wissensmeister',
  'badge.knowledge_master.desc': 'Schließe jedes Abenteuer ab.',

  'settings.title': 'Einstellungen',
  'settings.section.general': 'Allgemein',
  'settings.section.sound': 'Ton',
  'settings.section.accessibility': 'Barrierefreiheit',
  'settings.section.notifications': 'Erinnerungen',
  'settings.section.info': 'Informationen',
  'settings.section.data': 'Daten',
  'settings.language': 'Sprache',
  'settings.sound': 'Soundeffekte',
  'settings.soundDesc': 'Sanfte Töne für Tippen, Antworten und Belohnungen.',
  'settings.ambient': 'Hintergrundklang',
  'settings.ambientDesc': 'Ein ruhiges Windgeräusch im Hintergrund. Keine Musik.',
  'settings.haptics': 'Vibration',
  'settings.reducedMotion': 'Bewegung reduzieren',
  'settings.reducedMotionDesc': 'Weniger Animationen.',
  'settings.largeText': 'Größere Schrift',
  'settings.notif.dailyQuest': 'Erinnerung an das tägliche Abenteuer',
  'settings.notif.dailyReview': 'Erinnerung an die Wiederholung',
  'settings.notif.dailyChallenge': 'Erinnerung an die tägliche Herausforderung',
  'settings.notif.desc': 'Eine sanfte Erinnerung am Tag. Alle Erinnerungen sind freiwillig.',
  'settings.notif.denied': 'Erinnerungen sind blockiert. Du kannst Benachrichtigungen in den Telefoneinstellungen erlauben.',
  'settings.notif.unavailable': 'Erinnerungen sind auf diesem Gerät nicht verfügbar.',
  'settings.about': 'Über Islam Quest',
  'settings.privacy': 'Datenschutz',
  'settings.sources': 'Quellen',
  'settings.reset': 'Fortschritt zurücksetzen',
  'settings.resetDesc': 'Löscht Figur, XP, Abzeichen und Fortschritt auf diesem Gerät.',
  'settings.resetConfirmTitle': 'Gesamten Fortschritt zurücksetzen?',
  'settings.resetConfirmBody': 'Dadurch wird alles auf diesem Gerät gelöscht. Das kann nicht rückgängig gemacht werden.',
  'settings.resetConfirm': 'Ja, zurücksetzen',
  'settings.version': 'Version {version}',

  'about.title': 'Über Islam Quest',
  'about.p1': 'Islam Quest ist ein kostenloses Lernabenteuer für Kinder und Jugendliche. Es vermittelt die Grundlagen des Gebets, die Geschichten der Propheten, den Koran, guten Charakter, den Ramadan und Arabisch durch kurze Lektionen und Spiele.',
  'about.p2': 'Es gibt keine Werbung, keine Käufe und keine Konten. Alle Inhalte funktionieren offline.',
  'about.p3': 'Islam Quest ist ein Lernbegleiter. Die App erteilt keine Fatwas und ersetzt weder Eltern, Lehrkräfte, Imame noch richtigen Koran- und Arabischunterricht. Wo Gelehrte unterschiedliche Ansichten haben, sagt die App das.',
  'privacy.title': 'Datenschutz',
  'privacy.p1': 'Islam Quest sammelt, sendet und verkauft keine persönlichen Daten. Es gibt keine Werbung, keine Analyse und kein Tracking.',
  'privacy.p2': 'Dein Name, deine Figur und dein Fortschritt werden nur auf diesem Gerät gespeichert. Zurücksetzen oder Deinstallieren löscht sie.',
  'privacy.p3': 'Die App nutzt das Internet nur, wenn du bei einer Koranrezitation auf „Anhören“ tippst; der Ton wird dann vom Islamic Network CDN geladen. Alles andere funktioniert offline.',
  'privacy.p4': 'Erinnerungen sind lokale Benachrichtigungen auf deinem Gerät. Du kannst sie jederzeit ausschalten.',
  'sources.title': 'Quellen',
  'sources.intro': 'Die religiösen Inhalte dieser App beruhen auf dem Koran und bekannten Hadith-Sammlungen. Jede Lektion nennt ihre Belege.',
  'sources.quran': 'Korantext: Tanzil-Projekt (tanzil.net), Uthmani-Schrift, unverändert verwendet.',
  'sources.translations': 'Koranübersetzungen: Saheeh International (Englisch), Bubenheim & Elyas (Deutsch), Besim Korkut (Bosnisch).',
  'sources.hadith': 'Hadith-Belege: Sahih al-Bukhari, Sahih Muslim, Sunan Abi Dawud, Dschami’ at-Tirmidhi (übliche Nummerierung).',
  'sources.seerah': 'Prophetenbiografie: Ibn Hischam, As-Sira an-Nabawiyya.',
  'sources.recitation': 'Optionale Rezitation: Mishary Rashid Alafasy über cdn.islamic.network.',
  'sources.disclaimer': 'Die Geschichten werden in einfachen Worten nacherzählt, ohne Ereignisse oder Dialoge hinzuzufügen. Propheten werden nie bildlich dargestellt.',

  'notif.dailyQuest.title': 'Dein Abenteuer wartet',
  'notif.dailyQuest.body': 'Eine kurze Lektion heute hält dein Abenteuer am Laufen.',
  'notif.dailyReview.title': 'Zeit zum Wiederholen',
  'notif.dailyReview.body': 'Ein paar knifflige Fragen warten auf dich.',
  'notif.dailyChallenge.title': 'Tägliche Herausforderung',
  'notif.dailyChallenge.body': 'Die heutige Herausforderung ist bereit. Schaffst du sie?',
  'notif.channel': 'Lern-Erinnerungen',

  'ramadan.title': 'Ramadan-Reise',
  'ramadan.intro': 'Halte deine guten Taten für jeden Tag des Ramadan fest. Jede kleine Tat zählt!',
  'ramadan.safety': 'Ob und wie du das Fasten übst, entscheidest du immer gemeinsam mit deinen Eltern. Deine Gesundheit geht vor.',
  'ramadan.day': 'Tag {day}',
  'ramadan.deedsFor': 'Gute Taten an Tag {day}',
  'ramadan.total': 'Bisher {count} gute Taten',
  'ramadan.tip': 'Tipp des Tages',
  'ramadan.learnMore': 'Mehr über Ramadan lernen',
  'ramadan.locked': 'Öffne die Welt des Ramadan, um mehr über diesen Monat zu lernen.',

  'error.title': 'Etwas ist schiefgelaufen',
  'error.body': 'Keine Sorge – dein Fortschritt ist sicher. Bitte versuche es erneut.',
  'notFound.title': 'Seite nicht gefunden',
  'notFound.body': 'Diesen Ort gibt es auf der Karte nicht.',
  'notFound.home': 'Zur Startseite',

  'a11y.xpBar': '{xp} von {total} XP bis zur nächsten Stufe',
  'a11y.stars': '{count} von 3 Sternen',
  'a11y.speak': 'Aussprache abspielen',
  'a11y.closeQuest': 'Abenteuer schließen',
  'a11y.back': 'Zurück',
  'a11y.selected': 'ausgewählt',
  'a11y.correct': 'richtig',
  'a11y.incorrect': 'falsch',
  'a11y.card': 'Karte {index}',
  'a11y.hiddenCard': 'Verdeckte Karte {index}',
  'a11y.progress': 'Fortschritt {percent} Prozent',
  'a11y.avatar': 'Deine Figur',
};

export default de;
