const en = {
  'app.name': 'Islam Quest',

  'common.continue': 'Continue',
  'common.back': 'Back',
  'common.close': 'Close',
  'common.cancel': 'Cancel',
  'common.start': 'Start',
  'common.next': 'Next',
  'common.done': 'Done',
  'common.check': 'Check',
  'common.retry': 'Try again',
  'common.loading': 'Loading…',
  'common.locked': 'Locked',
  'common.xp': '{xp} XP',
  'common.level': 'Level {level}',
  'common.sources': 'Sources',
  'common.scholarsDiffer': 'Scholars differ',
  'common.save': 'Save',
  'common.on': 'On',
  'common.off': 'Off',

  'tabs.home': 'Home',
  'tabs.quest': 'Quest',
  'tabs.learn': 'Learn',
  'tabs.profile': 'Profile',

  'onboarding.step': 'Step {current} of {total}',
  'onboarding.welcome.title': 'Islam Quest',
  'onboarding.welcome.subtitle': 'An adventure through the worlds of Islamic knowledge. Learn, play, remember – and grow.',
  'onboarding.welcome.cta': 'Begin the adventure',
  'onboarding.language.title': 'Choose your language',
  'onboarding.language.subtitle': 'You can change it later in the settings.',
  'onboarding.character.title': 'Create your character',
  'onboarding.character.subtitle': 'This is you on your journey.',
  'onboarding.name.title': 'What should we call you?',
  'onboarding.name.subtitle': 'Your name stays only on this device.',
  'onboarding.name.placeholder': 'Your name',
  'onboarding.name.error': 'Please enter a name (1–20 characters).',
  'onboarding.explain.title': 'How the adventure works',
  'onboarding.explain.learn.title': 'Learn',
  'onboarding.explain.learn.body': 'Short lessons and stories from reliable sources.',
  'onboarding.explain.play.title': 'Play',
  'onboarding.explain.play.body': 'Quizzes, matching, ordering, memory and choices.',
  'onboarding.explain.remember.title': 'Remember',
  'onboarding.explain.remember.body': 'Tricky questions come back later so you really remember them.',
  'onboarding.explain.reward.title': 'Grow',
  'onboarding.explain.reward.body': 'Earn XP, level up, collect badges and unlock new worlds.',
  'onboarding.start.title': 'Your first quest awaits',
  'onboarding.start.body': 'The World of Salah is open. Discover what prayer is and why Muslims pray.',
  'onboarding.start.cta': 'Start first quest',
  'onboarding.start.later': 'Look around first',

  'character.title': 'Your character',
  'character.skin': 'Skin tone',
  'character.hair': 'Hair',
  'character.hairColor': 'Hair colour',
  'character.headwear': 'Headwear',
  'character.outfit': 'Outfit',
  'character.outfitColor': 'Outfit colour',
  'character.accessory': 'Accessory',
  'character.saved': 'Character saved',
  'character.hair.short': 'Short',
  'character.hair.curly': 'Curly',
  'character.hair.long': 'Long',
  'character.hair.buzz': 'Buzz cut',
  'character.hair.bun': 'Bun',
  'character.headwear.none': 'None',
  'character.headwear.kufi': 'Kufi',
  'character.headwear.hijab': 'Hijab',
  'character.headwear.cap': 'Cap',
  'character.outfit.thobe': 'Thobe',
  'character.outfit.hoodie': 'Hoodie',
  'character.outfit.jacket': 'Jacket',
  'character.outfit.abaya': 'Abaya',
  'character.accessory.none': 'None',
  'character.accessory.glasses': 'Glasses',
  'character.accessory.backpack': 'Backpack',
  'character.accessory.scarf': 'Scarf',
  'character.accessory.lantern': 'Lantern',
  'character.option': '{group}: {value}',

  'home.greeting': 'As-salamu alaykum, {name}!',
  'home.subtitle': 'What will you discover today?',
  'home.daily.title': 'Daily Challenge',
  'home.daily.body': 'One short challenge every day.',
  'home.daily.done': 'Completed today – see you tomorrow!',
  'home.continue.title': 'Continue your quest',
  'home.continue.allDone': 'You have completed every quest. Amazing!',
  'home.worlds': 'Your worlds',
  'home.review.title': "Let's Review",
  'home.review.count': '{count} questions are waiting',
  'home.review.empty': 'Nothing to review right now',
  'home.ramadan': 'Ramadan Journey',
  'home.ramadan.body': 'Calendar and good-deed tracker',

  'streak.label': 'Streak',
  'streak.days': '{count} days',
  'streak.day': '{count} day',
  'streak.today': 'You learned today',
  'streak.notToday': 'Learn something today to keep your streak',
  'streak.note': 'Your streak grows when you finish a lesson, quest, review or daily challenge.',

  'map.title': 'World Map',
  'map.subtitle': 'Complete quests to open new worlds.',
  'map.progress': '{done}/{total} quests',
  'map.lockedRequirement': 'Complete {count} quests in “{world}” to unlock',
  'map.complete': 'World complete',

  'world.quests': 'Quests',
  'world.lessons': 'Lessons in this world',
  'world.locked': 'This world is still locked.',
  'world.play': 'Play',
  'world.replay': 'Play again',
  'world.lockedQuest': 'Finish the previous quest first',
  'world.current': 'Next',
  'quest.kind.lesson': 'Lesson',
  'quest.kind.story': 'Story',
  'quest.kind.game': 'Mini games',
  'quest.kind.memorization': 'Memorisation',
  'quest.status.completed': 'Completed',
  'quest.status.available': 'Available',
  'quest.status.locked': 'Locked',
  'quest.steps': '{count} steps',

  'player.exitTitle': 'Leave this quest?',
  'player.exitBody': 'Your answers so far will not count as a finished quest.',
  'player.exit': 'Leave',
  'player.stay': 'Stay',
  'player.label.interactive': 'What do you think?',
  'player.label.challenge': 'Mini challenge',
  'player.label.quiz': 'Quiz',
  'player.correct': 'Correct!',
  'player.notQuite': 'Not quite',
  'player.correctAnswer': 'Correct answer: {answer}',
  'player.learnedTitle': 'What did we learn?',
  'player.story': 'Story',
  'player.addedToReview': 'Added to your review list',
  'player.notFound': 'This quest could not be found.',
  'player.locked': 'This quest is still locked.',

  'q.true': 'True',
  'q.false': 'False',
  'q.ordering.hint': 'Tap the items in the right order.',
  'q.ordering.reset': 'Start over',
  'q.matching.hint': 'Tap an item on the left, then its partner on the right.',
  'q.matching.mistakes': 'Mistakes: {count}',
  'q.memory.hint': 'Flip two cards to find a matching pair.',
  'q.memory.moves': 'Moves: {count}',
  'q.missingWord.hint': 'Choose the missing word.',
  'q.ayahOrder.hint': 'Tap the ayahs in the right order.',
  'q.scenario.title': 'What would you do?',

  'recite.title': 'Memorise: {surah}',
  'recite.hint': 'Read each ayah slowly and repeat it three times. Tap the ayah after each repetition.',
  'recite.repeat': '{count}/3',
  'recite.hideText': 'Test myself',
  'recite.showText': 'Show text',
  'recite.play': 'Listen',
  'recite.stop': 'Stop',
  'recite.audioUnavailable': 'Listening to the recitation needs an internet connection.',
  'recite.done': 'I practised this surah',
  'recite.makki': 'Makki',
  'recite.madani': 'Madani',
  'recite.ayahs': '{count} ayahs',
  'recite.source': 'Arabic text: Tanzil (Uthmani). Translation: {translation}.',
  'recite.basmalaNote': 'We begin with Bismillah.',
  'recite.remaining': 'Repeat every ayah 3 times to continue.',

  'tracing.title': 'Trace the letter',
  'tracing.hint': 'Follow the shape of the letter with your finger.',
  'tracing.clear': 'Clear',
  'tracing.next': 'Next letter',
  'tracing.listen': 'Listen',
  'tracing.keepGoing': 'Keep tracing…',
  'tracing.great': 'Great tracing!',
  'tracing.progress': 'Letter {current} of {total}',

  'lesson.listen': 'Listen',
  'lesson.done': 'I have read this',
  'lesson.locked': 'Unlock this lesson in the quest “{quest}”.',
  'lesson.notFound': 'This lesson could not be found.',
  'lesson.completed': 'Lesson completed',

  'reward.title': 'Quest complete!',
  'reward.score': '{correct} of {total} correct',
  'reward.lines.questComplete': 'Quest completed',
  'reward.lines.perfectBonus': 'Perfect score bonus',
  'reward.lines.worldComplete': 'World completed',
  'reward.lines.answers': 'Correct answers & lessons',
  'reward.noXp': 'You already earned the XP here – practising again still helps you remember!',
  'reward.levelUp': 'Level up! You are now level {level}.',
  'reward.newBadge': 'New badge unlocked!',
  'reward.worldUnlocked': 'New world unlocked: {world}',
  'reward.backToMap': 'Back to the map',
  'reward.reviewMistakes': 'Review my mistakes',
  'reward.xpTotal': '+{xp} XP',
  'reward.nextQuest': 'Next quest',
  'celebrate.levelTitle': 'Level up!',
  'celebrate.levelBody': 'You reached level {level}. Keep learning – every lesson makes you stronger!',

  'learn.title': 'Learn',
  'learn.subtitle': 'Read lessons again and practise what you found tricky.',
  'learn.review.title': "Let's Review",
  'learn.review.body': 'Questions you missed come back at the right time so you truly remember them.',
  'learn.review.cta': 'Start review',
  'learn.review.due': '{count} due now',
  'learn.review.none': 'No questions due',
  'learn.topics': 'Topics',
  'learn.lessonsCount': '{done}/{total} lessons',
  'learn.weakTopics': 'Topics to practise',
  'learn.quran': 'Quran memorisation',
  'learn.practised': 'Practised {count}×',
  'learn.notPractised': 'Not practised yet',
  'learn.worldLocked': 'Unlock this world on the map',

  'review.title': "Let's Review",
  'review.intro': 'These questions were tricky before. Let’s try them again!',
  'review.empty.title': 'All caught up!',
  'review.empty.body': 'There is nothing to review right now.',
  'review.empty.next': 'Next review: {date}',
  'review.empty.noItems': 'When you miss a question, it will appear here later.',
  'review.start': 'Start ({count})',
  'review.doneTitle': 'Review complete',
  'review.doneBody': 'You remembered {correct} of {total}. Mistakes are how we learn!',
  'review.mastered': 'Mastered',
  'review.box': 'Level {box}',

  'daily.title': 'Daily Challenge',
  'daily.kind.question': 'Question of the day',
  'daily.kind.miniQuiz': 'Mini quiz',
  'daily.kind.memory': 'Memory game',
  'daily.kind.fact': 'Did you know?',
  'daily.kind.scenario': 'What would you do?',
  'daily.doneTitle': 'Daily challenge complete!',
  'daily.alreadyDone': 'You already completed today’s challenge. Come back tomorrow for a new one!',
  'daily.factThenQuestion': 'Read the fact, then answer the question.',

  'profile.title': 'Profile',
  'profile.edit': 'Edit character',
  'profile.xpToNext': '{xp} XP to level {level}',
  'profile.badges': 'Badges',
  'profile.badgesCount': '{earned}/{total}',
  'profile.seeAll': 'See all',
  'profile.stats': 'Statistics',
  'profile.settings': 'Settings',
  'stats.quests': 'Quests completed',
  'stats.lessons': 'Lessons read',
  'stats.answers': 'Correct answers',
  'stats.accuracy': 'Accuracy',
  'stats.longestStreak': 'Longest streak',
  'stats.reviews': 'Reviews remembered',
  'stats.daily': 'Daily challenges',

  'badges.title': 'Badges',
  'badges.locked': 'Not earned yet',
  'badges.earnedOn': 'Earned on {date}',
  'badge.first_lesson.name': 'First Lesson',
  'badge.first_lesson.desc': 'Read your first lesson.',
  'badge.first_quest.name': 'First Quest',
  'badge.first_quest.desc': 'Complete your first quest.',
  'badge.prayer_explorer.name': 'Prayer Explorer',
  'badge.prayer_explorer.desc': 'Complete the World of Salah.',
  'badge.story_seeker.name': 'Story Seeker',
  'badge.story_seeker.desc': 'Complete the World of the Prophets.',
  'badge.quran_explorer.name': 'Quran Explorer',
  'badge.quran_explorer.desc': 'Complete the World of the Quran.',
  'badge.akhlaq_hero.name': 'Akhlaq Hero',
  'badge.akhlaq_hero.desc': 'Complete the World of Akhlaq.',
  'badge.ramadan_learner.name': 'Ramadan Learner',
  'badge.ramadan_learner.desc': 'Complete the World of Ramadan.',
  'badge.arabic_beginner.name': 'Arabic Beginner',
  'badge.arabic_beginner.desc': 'Complete the World of Arabic.',
  'badge.streak_7.name': '7 Day Streak',
  'badge.streak_7.desc': 'Learn on 7 days in a row.',
  'badge.streak_30.name': '30 Day Streak',
  'badge.streak_30.desc': 'Learn on 30 days in a row.',
  'badge.daily_learner.name': 'Daily Learner',
  'badge.daily_learner.desc': 'Complete 7 daily challenges.',
  'badge.review_champion.name': 'Review Champion',
  'badge.review_champion.desc': 'Remember 10 questions in review.',
  'badge.perfect_score.name': 'Perfect Score',
  'badge.perfect_score.desc': 'Finish a quest without a mistake.',
  'badge.world_explorer.name': 'World Explorer',
  'badge.world_explorer.desc': 'Unlock all six worlds.',
  'badge.knowledge_master.name': 'Knowledge Master',
  'badge.knowledge_master.desc': 'Complete every quest.',

  'settings.title': 'Settings',
  'settings.section.general': 'General',
  'settings.section.sound': 'Sound',
  'settings.section.accessibility': 'Accessibility',
  'settings.section.notifications': 'Reminders',
  'settings.section.info': 'Information',
  'settings.section.data': 'Data',
  'settings.language': 'Language',
  'settings.sound': 'Sound effects',
  'settings.soundDesc': 'Soft sounds for taps, answers and rewards.',
  'settings.ambient': 'Ambient sound',
  'settings.ambientDesc': 'A calm wind sound in the background. No music.',
  'settings.haptics': 'Vibration',
  'settings.reducedMotion': 'Reduce motion',
  'settings.reducedMotionDesc': 'Fewer animations.',
  'settings.largeText': 'Larger text',
  'settings.notif.dailyQuest': 'Daily quest reminder',
  'settings.notif.dailyReview': 'Daily review reminder',
  'settings.notif.dailyChallenge': 'Daily challenge reminder',
  'settings.notif.desc': 'One gentle reminder a day. All reminders are optional.',
  'settings.notif.denied': 'Reminders are blocked. You can allow notifications in your phone settings.',
  'settings.notif.unavailable': 'Reminders are not available on this device.',
  'settings.about': 'About Islam Quest',
  'settings.privacy': 'Privacy',
  'settings.sources': 'Sources',
  'settings.reset': 'Reset progress',
  'settings.resetDesc': 'Delete your character, XP, badges and progress on this device.',
  'settings.resetConfirmTitle': 'Reset all progress?',
  'settings.resetConfirmBody': 'This deletes everything on this device and cannot be undone.',
  'settings.resetConfirm': 'Yes, reset',
  'settings.version': 'Version {version}',

  'about.title': 'About Islam Quest',
  'about.p1': 'Islam Quest is a free educational adventure for children and young people. It teaches the basics of Salah, the stories of the prophets, the Quran, good character, Ramadan and Arabic through short lessons and games.',
  'about.p2': 'There are no advertisements, no purchases and no accounts. All content works offline.',
  'about.p3': 'Islam Quest is a learning companion. It does not give fatwas and does not replace parents, teachers, imams or formal Quran and Arabic lessons. Where scholars hold different views, the app says so.',
  'privacy.title': 'Privacy',
  'privacy.p1': 'Islam Quest does not collect, send or sell any personal data. There are no ads, no analytics and no tracking.',
  'privacy.p2': 'Your name, character and progress are stored only on this device. Resetting progress or uninstalling the app deletes them.',
  'privacy.p3': 'The app only uses the internet if you tap “Listen” on a Quran recitation; the audio is then loaded from the Islamic Network CDN. Everything else works offline.',
  'privacy.p4': 'Reminders are local notifications created on your device. You can switch them off at any time.',
  'sources.title': 'Sources',
  'sources.intro': 'Religious content in this app is based on the Quran and well-known hadith collections. Every lesson lists its references.',
  'sources.quran': 'Quran text: Tanzil Project (tanzil.net), Uthmani script, used without modification.',
  'sources.translations': 'Quran translations: Saheeh International (English), Bubenheim & Elyas (German), Besim Korkut (Bosnian).',
  'sources.hadith': 'Hadith references: Sahih al-Bukhari, Sahih Muslim, Sunan Abi Dawud, Jami’ at-Tirmidhi (standard numbering).',
  'sources.seerah': 'Seerah: Ibn Hisham, As-Sirah an-Nabawiyyah.',
  'sources.recitation': 'Optional recitation audio: Mishary Rashid Alafasy via cdn.islamic.network.',
  'sources.disclaimer': 'Stories are retold in simple words without adding events or dialogue. Prophets are never shown in pictures.',

  'notif.dailyQuest.title': 'Your quest is waiting',
  'notif.dailyQuest.body': 'A short lesson today keeps your adventure going.',
  'notif.dailyReview.title': "Let's review",
  'notif.dailyReview.body': 'A few tricky questions are ready for you.',
  'notif.dailyChallenge.title': 'Daily Challenge',
  'notif.dailyChallenge.body': 'Today’s challenge is ready. Can you solve it?',
  'notif.channel': 'Learning reminders',

  'ramadan.title': 'Ramadan Journey',
  'ramadan.intro': 'Track your good deeds for each day of Ramadan. Every small deed counts!',
  'ramadan.safety': 'Practising fasting is always decided together with your parents. Your health comes first.',
  'ramadan.day': 'Day {day}',
  'ramadan.deedsFor': 'Good deeds on day {day}',
  'ramadan.total': '{count} good deeds so far',
  'ramadan.tip': 'Tip of the day',
  'ramadan.learnMore': 'Learn about Ramadan',
  'ramadan.locked': 'Unlock the World of Ramadan to learn more about this month.',

  'error.title': 'Something went wrong',
  'error.body': 'Don’t worry – your progress is safe. Please try again.',
  'notFound.title': 'Page not found',
  'notFound.body': 'This place does not exist on the map.',
  'notFound.home': 'Go home',

  'a11y.xpBar': '{xp} of {total} XP towards the next level',
  'a11y.stars': '{count} of 3 stars',
  'a11y.speak': 'Play pronunciation',
  'a11y.closeQuest': 'Close quest',
  'a11y.back': 'Go back',
  'a11y.selected': 'selected',
  'a11y.correct': 'correct',
  'a11y.incorrect': 'incorrect',
  'a11y.card': 'Card {index}',
  'a11y.hiddenCard': 'Hidden card {index}',
  'a11y.progress': 'Progress {percent} percent',
  'a11y.avatar': 'Your character',
} as const;

export type TranslationKey = keyof typeof en;
export type Dictionary = Record<TranslationKey, string>;

export default en as Dictionary;
